### PR TITLE
Added list of required imports to android tutorial to avoid confusion wh...

### PR DESCRIPTION
**Pull request by jkitch20**
...en users are typing up the tutorial app, as well as provided link to API guide at bottom of the page.

### CODE REVIEW

**Comment by peplin** [comment]
I'm split on if we should add the imports - on the one hand it helps total newbies who don't know about Java imports, but on the other hand it sets them up to expect this to be a blind copy+paste tutorial, which it's definitely not supposed to be. What if instead we have a sentence about Java imports, and recommend the auto-import function in Eclipse to clean up all of the errors after putting in the code?

**Comment by jkitch20** [comment]
The reason I added this was because when I was going through it for the first time, I didn't realize at first that I was missing imports, so it wasn't clear.

I agree calling out the auto-import would be a good thing, but then you're leaving it to the developer to make sure they don't miss any. Could be frustrating to think you're all set, then have to go through a couple rounds of run->error->find the line->auto-import, repeat.

The other thing having these imports called out helps with is ensuring that you have the OpenXC library added to your project properly. If you don't, you'll see errors under the import lines, which will say "unable to find package" or something along those lines. The error when your java code can't find the required import is a little more ambiguous, if I recall. 

I did consider adding a line after the import saying something along the lines of "If you find you're still missing a required import, you can utilize Eclipses auto-import feature to pull in the necessary package." What if i add that after the import lines?

**Comment by peplin** [comment]
OK, we can include them, but could you put the required imports closer to the code that requires it (e.g. http://developer.android.com/training/basics/firstapp/starting-activity.html) and also leave out the Android imports that will already be there from the "first Android app" tutorial?

**Comment by jkitch20** [comment]
Perfect, makes total sense. I’ll make the changes

**Comment by jkitch20** [comment]
Chris, take a look and see if this fits what you were describing.

I noticed there were similarities in the tutorial and the API guide so I threw similar wording on the guide as well. The way it's laid out makes it clear where the classes are coming from while not making things as simple as copy-paste and not understand.
Thanks

**Comment by peplin** [comment]
Looks great, thanks!

**Pull request merged**
