### PR TITLE
Setup dev environment

### PR DESCRIPTION
**Pull request by jkitch20**
Updated library-installation.html to better document how to fully configure your dev station to get all the needed software up front. 

Also clarified the method for obtaining the android library to make use of the github release page for the openxc-android project.

### CODE REVIEW

**Comment by peplin** [comment]
Josh, can you take a look in the 'next' branch and see how this would fit in? This page became very much more Android-specific in the re-org so the Cygwin section may not be the best fit. If you merge in the 'next' branch into your 'setupDevEnvironment' branch, commit new stuff and re-push, it'll update this pull request.

**Comment by jkitch20** [comment]
Chris,

I have to leave for the day but I’ll try to take a look this evening when I get home. I merged the next branch and you’re right, this isn’t a good place for the Cygwin work anymore. I’ll include my other updates into the next branch version of this page and re-push, if not tonight then tomorrow morning. What time were you planning on doing the merge to production?
Thanks,
Josh

**Comment by peplin** [comment]
We can push it live tomorrow whenever you can get to it, no rush. I'll probably push the current version live tonight unless there are glaring issues or omissions.

**Comment by jkitch20** [comment]
I'm going to cancel this pull request as a lot of the content is no longer relevant/in the proper location since the redesign. I'll pull it apart manually and resubmit.

**Pull request closed without merging**
