### PR TITLE
Add Contributors Section

### PR DESCRIPTION
**Pull request by nathorne**
Added a Contributors Section

Added a "Contributors" landing page
Added a "How to Contribute" page
Added a "Contributors Tips & Tricks" page
Added a "Contributors" _layout bar for navigation within the Contributors section.
Modified top nav bar to link to the Contributors Landing Page

### CODE REVIEW

**Comment by nathorne** [comment]
Addressed #37

**Comment by peplin** [comment]
The content is good - I'd like to think about how we can fit this into the "Community" section since it duplicates some things.

**Comment by nathorne** [comment]
@peplin, while I do agree that there is some redundancy with the "Community" section, I still see a need for a "Contributors" landing page. If we do anything, I suggest removing some of the redundant bits and simply link to the "Community" page.

Thoughts?

**Comment by peplin** [comment]
I don't know if there's enough content to warrant being in the top nav. What if this was a sub-section under Community, i.e. in the left sidebar?

**Comment by nathorne** [comment]
I could see that... I tell you what, let me create another branch that moves this to the community section so we can compare.

**Comment by jkitch20** [comment]
My only issue with moving it to community is that I’m not sure that’s a very intuitive place for those looking for Contributors information to go look.
What if we look at putting it  under the “Other Resources” section of the left nav under the developers nav. That way the context of “contributing” is still
reaching the relevant target users.
Nick, could you perhaps add it to that area as well in your new branch, so we can see how it looks/feels? Then whatever we decide on, we can just update
your first branch and toss this test one.

-Josh

**Comment by nathorne** [comment]
@peplin and @jkitch20,

I've added two new branches in my personal repo based off this branch:

https://github.com/nathorne/openxcplatform.com/tree/contributorsToCommunity - Moves the "Contributors" pages to the "Community" section.

https://github.com/nathorne/openxcplatform.com/tree/contributorsToDevelopersOther - Moves the "Contributors" pages to the "Developers" section. 

Please review and let me know if you prefer either to this branch. If so, I can merge the selected branch into this branch.

**Comment by peplin** [comment]
I like the contributorsToCommunity branch, Nick, thanks.

**Pull request merged**
